spring:
  application:
    name: gateway-service
  datasource:
    url: jdbc:postgresql://localhost:5435/tracking_system_service
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
server:
  port: 8080
zuul:
  routes:
    auth-service:
      path: /auth/**
      serviceId: auth-service
      sensitiveHeaders:
    task-service:
      path: /task-tracker/**
      serviceId: task-service
      sensitiveHeaders:
  ignoredServices: "*"
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
auth-service:
  ribbon:
    listOfServers: localhost:8081
task-service:
  ribbon:
    listOfServers: localhost:8082