spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/tracking_system_security
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    change-log: "classpath:db/changelog/db.changelog-master.yml"
  application:
    name: auth-service
  security:
    oauth2:
      client:
        registration:
          accessTokenUri: http://localhost:8081/oauth/token
          userAuthorizationUri: http://localhost:8081/oauth/authorize
          clientId: webapp
          clientSecret: websecret
          userInfoUri: http://localhost:8081/user
server:
  port: 8081
logging:
  level:
    org:
      springframework:
        security: DEBUG
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default:
        zone: http://localhost:8761/eureka/
